site_name: NanoNode Homelab

theme:
  name: material

nav:
  - Home: index.md
  - Hardware:
      - Overview: hardware/overview.md
      - Power delivery:
        - Power Delivery: hardware/power-delivery/power-delivery-module.md
        - Power Delivery build log: hardware/power-delivery/pd-bl.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
