---
all:
  children:

    proxmox:
      hosts:
        POD042:
          ansible_host: 192.0.2.10
        POD153:
          ansible_host: 192.0.2.11
        POD006:
          ansible_host: 192.0.2.12