---
all:
  children:

    proxmox:
      hosts:
        pve01:
          ansible_host: 192.0.2.10
        pve02:
          ansible_host: 192.0.2.11
        pve03:
          ansible_host: 192.0.2.12

    lxc:
      children:
        infra:
          hosts:
            ct-forgejo:
              ansible_host: 192.0.2.23

    vms:
      children:
        automation:
          hosts:
            vm-homeassistant:
              ansible_host: 192.0.2.31
