---
proxmox_api_prereqs_packages:
  - python3-proxmoxer
  - python3-requests

proxmox_api_prereqs_trust_cluster_ca: true
proxmox_api_prereqs_ca_node: "{{ groups['proxmox'] | first }}"
proxmox_api_prereqs_ca_source: /etc/pve/pve-root-ca.pem
proxmox_api_prereqs_ca_dest: /usr/local/share/ca-certificates/pve-root-ca.crt